### ISSUE TITLE
Missing Header Files

### ISSUE THREAD

**Issue by bailey97** [tomdebree/TeslaBMSV2#1]
Hi tomdebree, 

I have downloaded all of the files provided here. However, when I try to compile/verify it in Arduino Studio I get errors for missing header files such as ADC.h and FlexCAN.h 
Is there somewhere else that I need to pull these files from? 

Thank you. Kind Regards,
Bailey

**Comment by stxShadow** [comment]
Look at the source code: 

#include <ADC.h> //https://github.com/pedvide/ADC
#include <FlexCAN.h> https://github.com/collin80/FlexCAN_Library 
#include <Filters.h>//https://github.com/JonHub/Filters
