### ISSUE TITLE
Balancing abormality

### ISSUE THREAD

**Issue by BobbyBleacher** [tomdebree/TeslaBMSV2#10]
See the screenshot there, Cells 20 and 21 keep bouncing back and forth between unusually high and low values. Unsure of the cause. Not documentation found to support this behavior.
![Screenshot 2019-09-20 16 31 13](https://user-images.githubusercontent.com/40462825/65360126-4fc69c80-dbc4-11e9-93b3-7532ce84f79e.png)

**Comment by BobbyBleacher** [comment]
If anyone else sees this, I found out way it probably is.

It's what happens when there is a bad connection to a cell, it senses a common mode voltage of two cells split between the two readings... ((4.87 + 2.57)/2) = 3.72

**Comment by tomdebree** [comment]
Alot of issues happen due to faulty wiring it is a pain to track down.
