### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by defuse53** [tomdebree/TeslaBMSV2#12]
Hello,

I cannot find the wiring diagram. Can you please help me?

Thanks in advance
defuse53

**Comment by BobbyBleacher** [comment]
Did you get it figured out?

**Comment by defuse53** [comment]
No I am still waiting for an answer.

**Comment by defuse53** [comment]
> Did you get it figured out?

No I am still waiting for help.

**Comment by tomdebree** [comment]
This made for the SimpBMS, check there.

**Comment by BobbyBleacher** [comment]
defuse, if you need help you can contact me. My email is is the google version. robertsmartinjr
