### ISSUE TITLE
PreCharge stays on

### ISSUE THREAD

**Issue by Webwanze** [tomdebree/TeslaBMSV2#15]
Hello,

in my opinion PreCharge should be switched off after main contactors are activated. 

- saves energy and wear
- prevents possible damages if main contactor fails 

Thomas

**Comment by tomdebree** [comment]
It goes off. Check your configuration.

**Comment by Webwanze** [comment]
I‘m in ESS mode. 
J4/2-GND
J4/13-PreCharge Relay

It stays on. Cannot find any settings. (Latest version)

**Comment by tomdebree** [comment]
Why are you running ESS mode and using pre charge? Read the manual…..

[cid:image003.png@01D5DD23.E0385640]

________________________________

**Comment by Webwanze** [comment]
Its a big battery for my home. This points to ESS. 
Also my SMA SunnyIsland should be precharged...

When using default mode:
After key in signal both contactors are closed the same time and precharge switches to off after a few seconds. 
I would expect first precharge - then main contactor - then precharge off.

**Comment by tomdebree** [comment]
Sure but are you using a SimpBMS?

Read the manual, ESS mode is NOT using precharge. An ESS installation requires manual precharging.

It does do this in the Normal mode. It does not require key in signal for ESS mode.

________________________________
