### ISSUE TITLE
"ihex: parse error line 1"

### ISSUE THREAD

**Issue by MrSlickShoes** [tomdebree/TeslaBMSV2#16]
When updating the hex file, getting error TeslaBMSV2.ino.TEENSY31.hex (unreadable)
Verbose information states "ihex: parse error line 1"
Teensy Loader 1.48
TeslaBMSV2.ino.TEENSY31.hex uploaded 7 days ago

**Comment by tomdebree** [comment]
I have created a new .HEX it works with my install of Teensyloader 1.48

**Comment by MrSlickShoes** [comment]
That fixed it! Thank you sir
