### ISSUE TITLE
Temperatur t0 prefix not shown on display

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#17]
Hi Tom,
t0.txt -> +- not shown

you forgot 

    Serial2.write(0x22);
    Serial2.write(0xff);
    Serial2.write(0xff);
    Serial2.write(0xff);

after

Serial2.write(0x22);
    if (bms.getAvgTemperature() > 0)
    {
      Serial2.print("+");
    }
    else
    {
      Serial2.print("-");
    }

**Comment by tomdebree** [comment]
Turns out there was no need for this.

**Comment by stxShadow** [comment]
agree .... temperature was not necessary 
but you also removes t7 (plus / minus) current ..... i find this very useful in ESS environments.

**Comment by tomdebree** [comment]
Turned out the display was already capable of this. the values are standard signed integers.
Please also check updated display firmware.
