### ISSUE TITLE
wrong value reset in battery settings menu

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#18]
If i set a value for "h" -> "j" will be reset to "0" 

h - Discharge Current Taper Offset: 300mV  
j - Discharge Current Temperature Derate : 40.00C  

h 200

after that: 

h - Discharge Current Taper Offset: 200mV  
j - Discharge Current Temperature Derate : 0.00C

**Comment by tomdebree** [comment]
Thanks for the catch, for got a few “Break;” after case declarations.

________________________________

**Comment by stxShadow** [comment]
You are welcome :)

Hope you got my mail to you gmail account too ? Regarding SOC and Victron ESS.
