### ISSUE TITLE
CONFIG.H / Linux

### ISSUE THREAD

**Issue by rfuegen** [tomdebree/TeslaBMSV2#19]
Linux is case sensitive. compiling TeslaBMS in arduino studio fails because of #include "config.h" 

since windows is not case sensitive, it would be a nice gesture to linux users to rename CONFIG.H to config.h.

**Comment by stxShadow** [comment]
yes .... same here ..... have to softlink to config.h on every new checkout

**Comment by tomdebree** [comment]
changed, I was not aware of this. Also had to do it in the web interface of github otherwise it would not upload the case change.
