### ISSUE TITLE
SMA Sunny Island 6048 CAN support?

### ISSUE THREAD

**Issue by jwthecolorist** [tomdebree/TeslaBMSV2#20]
Hello! I saw on a previous issue that it was asked if the Sunny Island units were supported and I see someone using it with a 6.0H. I was wondering if this support also covers the 6048 model?

Thank you.

**Comment by tomdebree** [comment]
I have no idea, yes some sunny island inverters are supported. Please check if it supports the same batteries, if it does it should work.

Regards,

Tom
