### ISSUE TITLE
SOC not updating

### ISSUE THREAD

**Issue by jono230981** [tomdebree/TeslaBMSV2#25]
Hi,

I flashed the latest version onto the BMS this morning . The cell voltages update but the SOC holds steady at whatever value it calculated when booted. regardless of any charge/discharge. Resetting the BMS and the SOC is correctly calculated during boot but then fails to refresh going forward. This value is also reflected on by Victron CX too, hence the frozen value is passed accross the CAN.  The total pack voltage ( in my case something around 48v ) is correctly displayed and also updated depending on charge level. 

I have 2 Tesla Packs in Series. ( 48v) configuration

thanks

**Comment by Tom-evnut** [comment]
Check the settings in the current sensor menu. Are those still correct? Has this behaviour only occurred after the update and was it working before?

**Comment by jono230981** [comment]
Thank you for responding so quickly.  My system has only recently been commissioned hence I do not have a huge amount of back data/observations ,  as far as I know the SoC was working correctly before ( im pretty confident!) I confess to not being 100% certain. I'm using a Victron VE-Shunt which connects directly to the GX for current measurements, hence its not on the BUS.  So Im assuming the  SIMPBMS would never receive this data. 

Ive changed the current sensor settings as follows and ill monitor tonight/tomorrow to see if the SoC updates. 
Please let me know if there is something specific I should set. 

many thanks 

Current Sensor Calibration Menu
c - To calibrate sensor offset
s - Current Sensor Type : Undefined
1 - invert current :0
2 - Pure Voltage based SOC :1
3 - Current Multiplication :1
q - Go back to menu

**Comment by Tom-evnut** [comment]
Yes that should be the way. Please check the SOC voltage settings in the battery settings are at a logical levels.
