### ISSUE TITLE
only cosmetical -> double display value

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#3]
Serial2.print("firm.val=");
  Serial2.print(firmver);
  Serial2.write(0xff);  // We always have to send this three lines after each command sent to the nextion display.
  Serial2.write(0xff);
  Serial2.write(0xff);
  Serial2.print("firm.val=");
  Serial2.print(firmver);
  Serial2.write(0xff);  // We always have to send this three lines after each command sent to the nextion display.
  Serial2.write(0xff);

Double serial output of the firmware version to Nextion Display.

It would be quite nice to have a page with the actual cell voltages .... 

Maybe i can contribute that to your project ? 

Jens

**Comment by stxShadow** [comment]
just to simplify the write(0xff):

you can do:
byte NextionTerminator[3] = {255,255,255}; // global declaration

Serial2.print("firm.val=");
Serial2.print(firm);
Serial2.write(NextionTerminator,3);

etc ..... should shorten the whole thing

**Comment by tomdebree** [comment]
Fix implemented, will think about the shortening of coding with the array.
