### ISSUE TITLE
Bug "R" -> restart not working

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#5]
Firmware Version : 190729

Pressing "R" to restart the BMS is not working. The serial connection is reseted but the device is not coming back to life.

**Comment by stxShadow** [comment]
Follow up -> to get reboot working change 
#define CPU_REBOOT (_reboot_Teensyduino_());
to 
#define RESTART_ADDR       0xE000ED0C
#define READ_RESTART()     (*(volatile uint32_t *)RESTART_ADDR)
#define WRITE_RESTART(val) ((*(volatile uint32_t *)RESTART_ADDR) = (val))
#define CPU_REBOOT (WRITE_RESTART(0x5FA0004));
-> restart is working fine after that

**Comment by BobbyBleacher** [comment]
Is this right? It won't compile for me.

**Comment by stxShadow** [comment]
works quite nice for me. What error are you seeing ? My own little fork looks like this -> line 33 to 42:

#include <SPI.h>
#include <Filters.h>//https://github.com/JonHub/Filters

#define RESTART_ADDR       0xE000ED0C
#define READ_RESTART()     (*(volatile uint32_t *)RESTART_ADDR)
#define WRITE_RESTART(val) ((*(volatile uint32_t *)RESTART_ADDR) = (val))
#define CPU_REBOOT (WRITE_RESTART(0x5FA0004));

BMSModuleManager bms;
SerialConsole console;

**Comment by BobbyBleacher** [comment]
TeslaBMSV2: In function 'void menu()':
TeslaBMSV2:35: error: lvalue required as left operand of assignment
 #define WRITE_RESTART(val) (((volatile uint32_t *)RESTART_ADDR) = (val))

                                                                 ^

C:\Users\Bobby Martin\Dropbox\arduino-1.8.8\portable\sketchbook\TeslaBMSV2\TeslaBMSV2.ino:36:21: note: in expansion of macro 'WRITE_RESTART'

 #define CPU_REBOOT (WRITE_RESTART(0x5FA0004));

                     ^

C:\Users\Bobby Martin\Dropbox\arduino-1.8.8\portable\sketchbook\TeslaBMSV2\TeslaBMSV2.ino:2252:9: note: in expansion of macro 'CPU_REBOOT'

         CPU_REBOOT ;

         ^

**Comment by tomdebree** [comment]
Fix implemented, works now.
