### ISSUE TITLE
Bug: SOC Setpoint 1 -> wrong value

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#7]
Setting "Discharge Current Taper" sets "SOC Setpoint 1" to zero -> see attached picture.

![bug](https://user-images.githubusercontent.com/48672214/64285403-0c312900-cf5c-11e9-8d08-c6bb5564edf4.png)

**Comment by tomdebree** [comment]
switchcase order changed to fix
