### ISSUE TITLE
Nextion stat.txt stuck to "boot" in ESS Mode

### ISSUE THREAD

**Issue by stxShadow** [tomdebree/TeslaBMSV2#8]
The stat.txt field in nextion displays never geht to "ready" in ESS Mode. 

Value is stuck in "boot".

**Comment by stxShadow** [comment]
As far as i see there is no other output than "boot" if in ESS Mode.
Maybe you should send something like "ESS Aktive".

**Comment by stxShadow** [comment]
changed the code like this:

void dashupdate()
{
  Serial2.write("stat.txt=");
  Serial2.write(0x22);
 
  if ((settings.ESSmode == 1) && (bmsstatus != Error))
  {   
      //In ESS mode print only ESS Active / Error messages to the nextion display
      Serial2.print("ESS Active");
  }
  else
  {
    switch (bmsstatus)

works for my case now

**Comment by tomdebree** [comment]
Sorry the screen was mainly meant for Vehicle operation so none ESS mode, will roll this change into code.
